main/urls.py
from django.urls import path, include
from .views import Blog_main, Blog_post, Blog_list, Blog_crud, Main_category_make, Blog_list_crud, My_page,\
    Re_post_list
from django.conf.urls.static import static
from django.conf import settings
app_name = 'main'

urlpatterns = [
    path('post/<int:pk>', Blog_post.as_view(), name='blog_post'),
    path('cate_set/<str:cate>', Main_category_make.as_view(), name='main_category_make'),
    path('list_crud/<str:cate>', Blog_list_crud.as_view(), name='blog_list_crud'),
    path('list/<str:cate>', Blog_list.as_view(), name='blog_list'),
    path('crud/<int:pk>', Blog_crud.as_view(), name='blog_crud'),
    path('', Blog_main.as_view(), name='blog'),
    path('mypage', My_page.as_view(), name='mypage'),
    path('re_post_list/<int:pk>', Re_post_list.as_view(), name='re_post_list'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro/urls.py
from django.urls import re_path as url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from main.views import Blog_main
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('main.urls')),
    path('', Blog_main.as_view(), name='Blog'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('account.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

main/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, AbstractUser
from ckeditor.fields import RichTextField


class BaseModel(models.Model):
    modify_date = models.DateTimeField(auto_now=True)
    create_date = models.DateTimeField(auto_now_add=True)
    class Meta:
        abstract = True

class Category(models.Model): # 상위 카테고리
    category_name = models.CharField(max_length=50, unique=True)
    CATEGORY_TITLE = (
        ('Stack', 'Stack'),
        ('Language', 'Language'),
        ('CSS', 'CSS'),
        ('Basic', 'Basic'),)
    category_title = models.CharField(verbose_name='category', choices=CATEGORY_TITLE, blank=True, max_length=10)

    def __str__(self):
        return self.category_name

class Blog(BaseModel): # 하위 카테고리
    title = models.CharField(max_length=50)
    sub_title = models.TextField(blank=True)
    img = models.ImageField(upload_to="Blog_image")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

class Sub_blog(BaseModel): # 하위 카테고리 내의 글
    subtitle = models.CharField(max_length=100)
    content = RichTextField('내용', blank=True)
    code_set = models.TextField(blank=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)

templates/blog/CRUD.html
<!DOCTYPE html>
<html lang="en">
{% extends "blog/blog_base.html" %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>게시글 작성</title>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link rel="stylesheet" href="{% static 'css/blog/blog_post_style.css' %}" />
</head>
<body>
<div class="container2" style="margin-top: 40px; margin-bottom: 40px">
    <span class="span_font" style="font-weight: bold; font-size: 50px; color: #27AE60;">Write a post.</span>

</div>
<form action="{% url 'main:blog_crud' pk=pk %}" method="POST" novalidate class="container2">
        {% csrf_token %}
    <div>
    <div style="margin-bottom: 40px;">
        <label for="subtitle" class="span_font crud_label">Title</label>
        <input class="title span_font" style="margin-top: 10px" type="text" id="subtitle" name="subtitle" required
                    value="{{ form.subtitle.value|default_if_none:'' }}"></div>
    <div style="display: block; margin-bottom: 40px" >
        <div style="margin-bottom: 10px;">
        <span class="span_font" style="font-size: 20px; font-weight: bold">Content</span></div>
    <textarea class="ckeditor" name="content" id="content">{{ form.content.value|default_if_none:'' }}</textarea></div>
    <div style="margin-bottom: 40px">
        <label for="codepen" class="span_font crud_label">Code pen</label>
    <textarea style="margin-top: 10px" class="codepen" id="codepen" name="code_set">
        {{ form.code_set.value|default_if_none:'' }}
    </textarea></div>
        <div class="container2" style="margin-top: 20px">
            <div class="crud_button container2">
        <button type="submit">MAKE</button></div></div>
</div>
</form>
<script>// CKEditor를 textarea에 적용
  ClassicEditor
    .create(document.querySelector('#content'))
    .catch(error => {
      console.error(error);
    });</script>
</body>
{% endblock %}
</html>

templates/blog/blog.html
<!DOCTYPE html>
<html lang="en">
{% extends "blog/blog_base.html" %}
{% load static %}
{% block content %}
<head>
<style>
        body {
            background-image: url({% static 'img/Laptop.png' %});
            background-size: cover;
            background-attachment: fixed; /* 배경 이미지를 고정시킵니다. */
        }
    </style>
    <meta charset="UTF-8">
    <title>blog_test</title>
</head>
<body>
<div style="height: 100%; position: relative; ">
<div class="container_y" style="height: 60px; padding-top: 100px ">
    <a href="{% url 'main:blog' %}">
    <div style="margin-left: 20px; margin-top: 50px">
        <img style="height: 300px; opacity: 1; max-width: none" src="{% static 'img/DoDay5.png'%}">
    </div></a>
    <div style="left: 55%;transform: translateX(-55%); position: absolute">
    {% include "blog/blog_bar.html" %}</div>
</div>
<div class="container2" style="height: 535px">
    <span class="font_set" style="color: white; font-size: 60px; margin-right: 20px">{{ post.title }}</span>
        </div>
    <div style="position: absolute;
      bottom: 0;
      width: 100%;">
<svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
        </defs>
        <g class="parallax">
            <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255, 255, 255,0.7)"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255, 255, 255,0.5)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255, 255, 255,0.3)"/>
            <use xlink:href="#gentle-wave" x="48" y="7" fill="rgba(255, 255, 255,1)"/>
        </g>
</svg></div></div>
<div style="background-color: #cccccc; z-index: -2;">
<div class="container2 blog_shadow" style="padding-top: 50px; padding-bottom: 50px;
margin-bottom: 10px; background-color: white">
        <div class="blog_index blog_shadow">
            <div class="blog_index_box"><div class="bar_font blog_index_font" style="color: black; font-size: 25px">
                <div style="margin-right: 5px">📒</div>목차</div>
            <div class="container2" style="margin-right: 10px"><a href="{% url 'main:blog_crud' pk=blog_id%}"><img style="height: 30px;" src="{% static 'img/yellow_plus.png'%}">
            </a>
            </div>
            </div>
            {% for box in post_box %}
            <a href="#{{ box.id }}"><div class="blog_index_box">
                <div class="blog_index_font blog_index_hover">
                    <div style="margin-right: 5px">●</div>{{ box.subtitle }}
                </div>
            </div></a>
                <script>document.querySelector("a[href='#{{ box.id }}']").addEventListener("click", function(event) {
    // 기본 동작(링크 이동)을 막습니다.
    event.preventDefault();

    // 대상 div의 위치를 가져옵니다.
    const targetDiv = document.getElementById("{{ box.id }}");

    // 대상 div의 위치로 스크롤을 이동합니다.
    targetDiv.scrollIntoView({ behavior: 'smooth' });
});</script>
            {% endfor %}
        </div>
    </div>
    </div>
{% for box in post_box %}
<div id="{{ box.id }}" class="container2 blog_shadow" style="padding-top: 50px; padding-bottom: 50px;
margin-bottom: 10px; background-color: white">
    <div>
    <div class="blog_subtitle" style="border-bottom: #fccd4e solid 1px">{{ box.subtitle }}</div>
        <div class="blog_subtitle" style="font-size: 14px;">{{ box.content | safe }}</div>
    <div style="width: 900px">
        {{ box.code_set | safe }}</div>
    </div></div>
{% endfor %}
</body>
{% endblock %}
</html>

templates/blog/blog_bar.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% block content %}
<head>
    <title></title>
</head>
<body>
<div class="container_y menu" style="justify-content: space-around; background-color: rgb(0,0,0,0.3); width: 1000px; border-radius: 40px; height: 60px;">
    <ul style="display: flex;
    justify-content: space-around;width: 100%">
            <li><a href="#"><span class="blog_bar_font container2" style="color: #f7ca8d; font-size: 25px; opacity: 0.7">Stack
        <span style="font-size: 20px" class="degree">◀</span></span></a>
                <ul class="submenu">
                    {% for stack in stack %}
                    <li><a class="bar_font" href="{% url 'main:blog_list' cate=stack %}">{{ stack.category_name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <li><a href="#"><span class="blog_bar_font container2" style="color: #f7ca8d; font-size: 25px; opacity: 0.7">Lenguge
        <span style="font-size: 20px" class="degree">◀</span></span></a>
                <ul class="submenu">
                    {% for lenguge in lenguge %}
                    <li><a class="bar_font" href="{% url 'main:blog_list' cate=lenguge %}">{{ lenguge.category_name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <li><a href="#"><span class="blog_bar_font container2" style="color: #f7ca8d; font-size: 25px; opacity: 0.7">CSS
    <span style="font-size: 20px" class="degree">◀</span></span></a>
                <ul class="submenu">
                    {% for css in css %}
                    <li><a class="bar_font" href="{% url 'main:blog_list' cate=css %}">{{ css.category_name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        <li><a href="#"><span class="blog_bar_font container2" style="color: #f7ca8d; font-size: 25px; opacity: 0.7">Basic
    <span style="font-size: 20px" class="degree">◀</span></span></a>
                <ul class="submenu">
                    {% for basic in basic %}
                    <li><a class="bar_font" href="{% url 'main:blog_list' cate=basic %}">{{ basic.category_name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        </ul></div>
{% endblock %}
</body>
</html>

templates/blog/blog_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% block content %}
{% endblock %}
<head>
    <title></title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@3.7.3/dist/full.css"
      rel="stylesheet"
      type="text/css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/set.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/page_3.css' %}" />
    <link rel="stylesheet" href="{% static 'css/blog/blog_set.css' %}" />
    <link rel="stylesheet" href="{% static 'css/test.css' %}" />
    <script defer src="{% static 'js/blog/blog_main_font.js' %}"></script>
    <script defer src="{% static 'js/test.js' %}"></script>
    <script defer src="{% static 'js/blog/CRUD.js' %}"></script>
    <script defer src="{% static 'js/blog/menu_bar.js' %}"></script>
    <script defer src="{% static 'js/blog/blog_list.js' %}"></script>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="https://kit.fontawesome.com/c47106c6a7.js" crossorigin="anonymous"></script>
    <script>history.scrollRestoration="manual"</script>
</head>
</html>

templates/blog/blog_list.html
<!DOCTYPE html>
<html lang="en">
{% extends "blog/blog_base.html" %}
{% load static %}
{% block content %}
    <head>
    <link rel="stylesheet" href="{% static 'css/blog/blog_list.css' %}" />
        <link rel="stylesheet" href="{% static 'css/blog/blog_list_main_font.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
        body {
            background-image: url({% static 'img/blog_list.jpg' %});
            background-color: rgba(252, 224, 179, 1);
            background-size: cover;
            background-attachment: fixed; /* 배경 이미지를 고정시킵니다. */
        }
    </style>
    <title>List</title>
</head>
<body>
<div style="height: 90%;position: relative;">
<div class="container_y" style="height: 60px; padding-top: 100px ">
    <a href="{% url 'main:blog' %}">
    <div style="margin-left: 20px; margin-top: 50px">
        <img style="height: 300px; opacity: 1; max-width: none" src="{% static 'img/DoDay5.png'%}">
    </div></a>
    <div style="left: 55%;transform: translateX(-55%); position: absolute">
    {% include "blog/blog_bar.html" %}</div>
</div>
<div class="container2">
    <div class="container2" style="margin-top: 110px">
<div class="container2" style="width: 1200px">
<div style="display: block;">
    <div class="floating-div container2" id="animatedDiv" style="width: 100%">
        <span>{{ title_name }}</span>
    </div>
<div class="list-line">
<img src="{% static 'img/list_bottom_line.png' %}"></div>
</div>
</div>
</div>
        </div>
    <div class="search-wrapper" style="margin-top: 100px">
    <div class="input-holder">
        <input type="text" class="search-input" placeholder="Type to search" />
        <button class="search-icon" onclick="searchToggle(this, event);"><span></span></button>
    </div>
    <span class="close" onclick="searchToggle(this, event);"></span>
</div>
    <div style="position: absolute;
      bottom: 0;
      width: 100%;">
<svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
        </defs>
        <g class="parallax">
            <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(252, 224, 179,0.7)"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(252, 224, 179,0.5)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(252, 224, 179,0.3)"/>
            <use xlink:href="#gentle-wave" x="48" y="7" fill="rgba(252, 224, 179,0.8)"/>
        </g>
</svg></div></div>
    <div style="background-color: rgba(255, 233, 199, 1);">
    <div style="padding-top: 20px; padding-bottom: 100px">
        <div class="container2" style="margin-bottom: 30px">
        <div class="typing-demo">
      Knowledge is power.
    </div></div>
        <div class="container2">
    <div class="list_con" style="width: 1120px">
        {% for blog in blog %}
        <div class="scrolling-div">
            <a href="{% url 'main:blog_post' pk=blog.id %}">
    <div class="blog_set hover-shadow" style="width: 350px; height: 450px; border: lightgray solid 0.5px; border-radius: 25px">
            <div style="height: 200px; position: relative; overflow: hidden">
                <img style="border-radius: 25px 25px 0 0" src="{{ blog.img.url }}"></div>
            <div class="container2">
                <div>
            <div class="span_font" style="margin-top: 20px; width: 300px; height: 200px;">
                <div style="color: black;
             font-weight: bold; font-size: 18px; height: 60px">
                💻 {{ blog.title }}</div>
                <div class="span_font" style="color: gray; margin-top: 5px; font-size: 15px; height: 135px; word-wrap: break-word;
                 overflow: hidden; text-overflow: ellipsis;">
                {{ blog.sub_title }}</div>
            </div></div></div></div></a></div>
        {% endfor %}

    </div></div></div></div>
{% endblock %}
</body>
</html>

templates/blog/blog_main.html
<!DOCTYPE html>
<html lang="en">
{% extends "blog/blog_base.html" %}
{% load static %}
{% block content %}
<head>
<link rel="stylesheet" href="{% static 'css/blog/blog_main.css' %}" />
<style>
</style>
    <meta charset="UTF-8">
    <title>DoDay!blog</title>
<style>
    .menu :where(li ul){
        padding-left: 0 !important;
    }

    .image1{
        background-image: url({% static 'img/blog_image_set.png' %});
        background-size: cover;
    }
    .image2{
        background-image: url({% static 'img/blog_page22.png' %});
        background-size: cover;
    }
    .image3{
        background-image: url({% static 'img/check.png' %});
        background-size: cover;
    }
</style>
    <link rel="stylesheet" href="{% static 'css/main_font.css' %}" />
<script defer src="{% static 'js/blog/blog_main.js' %}"></script>
<script defer src="{% static 'js/main_font.js' %}"></script>
</head>
<body>
<div class="box image1">

<div class="container_y" style="height: 60px; padding-top: 100px ">
    <a href="{% url 'main:blog' %}">
    <div style="margin-left: 20px; margin-top: 50px">
        <img style="height: 300px; opacity: 1; max-width: none" src="{% static 'img/DoDay5.png'%}">
    </div></a>
    <div style="left: 55%;transform: translateX(-55%); position: absolute">
    {% include "blog/blog_bar.html" %}</div>
</div>{% if user.is_authenticated %}
        <div style="left: 93%;transform: translateX(-93%); top: 6%; position: absolute; border: solid white;
            border-radius: 10px">
        <div>
        <a href="{% url 'main:mypage' %}"><img style="height: 100px; opacity: 1; max-width: none" src="{% static 'img/admin_image.png'%}"></a>
    </div></div>{% endif %}
<div style="height: 150px"></div>
<div class="container" style="font-size: 30px">
    <p>Coding is <span class="typed-text"></span><span class="cursor">&nbsp;</span></p>
  </div>

    <div class="moving-box">
        <div class="moving-div">
        <img width="100px" src="{% static "img/main_arrow.png" %}"></div>
    </div>
</div>
    <div class="box image2">
        <div class="container2" style="height: 100%">
            <div>
<div class="container2">
        <div style="width: 1000px; margin-bottom: 20px; padding-left: 10px; display: flex">
            <div>
            <span class="span_font" style="color: #f7ca8d; font-weight: bold; font-size: 30pt"> 📚Recent post</span>
            <span class="span_font" style="color: gray; font-size: 15px">따끈따근 하게 올라온 최신 포스팅을 구경해보세요 !</span>
            </div>
        </div></div>
<div class="container2">
        {% include "page_3.html" %}
    </div>
    </div>
            </div>
        </div>
<div class="box image3">
    <div class="container2" style="height: 100%">
        <div>
    <div class="container2">
        <span class="span_font" style="color: #f7ca8d; font-weight: bold; font-size: 30pt; margin-right: 20px"> 📚Popular Categories</span>
            <span class="span_font" style="color: gray; font-size: 15px; padding-top: 10px">잘 정리된 다양한 카테고리를 둘러보세요 !</span></div>
    <div class="container2" style="margin-top: 80px">
        <div>
        <div class="container2" style="width: 1000px; top: 50%; justify-content: space-around">
            <a href="#">
            <div class="page3_box blog_set1 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/django.png' %}"></div>
                <div class="container2"><span class="pg3_font">Django</span></div></div>
            </div></a>
            <a href="#">
            <div class="page3_box blog_set1 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/spring.png' %}"></div>
                <div class="container2"><span class="pg3_font">Spring</span></div></div>
            </div></a>
            <a href="#">
            <div class="page3_box blog_set1 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/aws.png' %}"></div>
                <div class="container2"><span class="pg3_font">Server</span></div></div>
            </div></a>
            <a href="#">
            <div class="page3_box blog_set1 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/html.png' %}"></div>
                <div class="container2"><span class="pg3_font">Html</span></div></div>
            </div></a>
        </div>
            <div class="container2" style="margin-top: 70px; width: 1000px; top: 50%; justify-content: space-around">
            <a href="#">
            <div class="page3_box blog_set2 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/git.png' %}"></div>
                <div class="container2"><span class="pg3_font">Git</span></div></div>
            </div></a>
            <a href="#">
            <div class="page3_box blog_set2 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/css.png' %}"></div>
                <div class="container2"><span class="pg3_font">CSS</span></div></div>
            </div></a>
            <a href="#">
            <div class="page3_box blog_set2 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/javascript.png' %}"></div>
                <div class="container2"><span class="pg3_font">JavaScript</span></div></div>
            </div></a>
            <a href="#">
            <div class="page3_box blog_set2 hover-shadow container2">
                <div>
                    <div class="container2">
                <img style="height: 50%; width: 50%" src="{% static 'img/beginner.png' %}"></div>
                <div class="container2"><span class="pg3_font">Beginner</span></div></div>
            </div></a>
        </div>
            </div>
    </div>
</div>
    </div>
    </div>
</body>
{% endblock %}
</html>

templates/blog/my_page.html
<!DOCTYPE html>
<html lang="en">
{% extends "blog/blog_base.html" %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>메인 카테고리</title>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link rel="stylesheet" href="{% static 'css/blog/blog_post_style.css' %}" />
<link rel="stylesheet" href="{% static 'css/blog/mypage.css' %}" />
</head>
<body>
<div class="container2" style="margin-top: 40px; margin-bottom: 40px">
    <span class="span_font" style="font-weight: bold; font-size: 50px; color: #27AE60;">Admin Page.</span>

</div>
<div class="container_x">
    <div class="container_x" style="width: 200px">
        <div>
        <div class="mypage_title container2">
            <span style="margin-right: 5px" class="span_font mypage_font">Stack</span>
            <a href="{% url 'main:main_category_make' cate="Stack" %}"><img style="height: 17px;" src="{% static 'img/yellow_plus.png'%}"></a> </div>
        <div class="container2" style="margin-top: 20px">
            <div>
                {% for stack in stack %}
            <div class="span_font mypage_font container_x">
                <a style="margin-right: 5px" href="{% url 'main:blog_list' cate=stack %}">{{ stack.category_name }}</a>
                <div class="container_y">
            <a href="{% url 'main:blog_list_crud' cate=stack.category_name %}">
                <img style="height: 17px;" src="{% static 'img/green_plus.png'%}"></a>
                <a href="{% url 'main:blog_list' cate='re_'|add:stack.category_name %}">
                <img style="height: 17px;" src="{% static 'img/green_plus.png'%}"></a></div>
            </div>
            {% endfor %}
                </div>
        </div>
        </div>
    </div>
    <div class="container_x" style="width: 200px">
        <div>
        <div class="mypage_title container2">
            <span style="margin-right: 5px" class="span_font mypage_font">Lenguge</span>
            <img style="height: 17px;" src="{% static 'img/yellow_plus.png'%}"> </div>
        <div class="container2" style="margin-top: 20px">
            <div>
                {% for lenguge in lenguge %}
            <div class="span_font mypage_font container_x">
                <a style="margin-right: 5px" href="{% url 'main:blog_list' cate=lenguge %}">{{ lenguge.category_name }}</a>
            <div class="container_y">
            <a href="{% url 'main:blog_list_crud' cate=lenguge.category_name %}">
                <img style="height: 17px;" src="{% static 'img/green_plus.png'%}"></a></div>
            </div>
            </div>
            {% endfor %}
                </div>
        </div>
        </div>
    </div>
    <div class="container_x" style="width: 200px">
        <div>
        <div class="mypage_title container2">
            <span style="margin-right: 5px" class="span_font mypage_font">CSS</span>
            <img style="height: 17px;" src="{% static 'img/yellow_plus.png'%}"> </div>
        <div class="container2" style="margin-top: 20px">
            <div>
                {% for css in css %}
            <div class="span_font mypage_font container_x">
                <a style="margin-right: 5px" href="{% url 'main:blog_list' cate=css %}">{{ css.category_name }}</a>
            <div class="container_y">
            <a href="{% url 'main:blog_list_crud' cate=css.category_name %}">
                <img style="height: 17px;" src="{% static 'img/green_plus.png'%}"></a></div>
            </div>
            {% endfor %}
                </div>
        </div>
        </div>
    </div>
    <div class="container_x" style="width: 200px">
        <div>
        <div class="mypage_title container2">
            <span style="margin-right: 5px" class="span_font mypage_font">Basic</span>
            <img style="height: 17px;" src="{% static 'img/yellow_plus.png'%}"> </div>
        <div class="container2" style="margin-top: 20px">
            <div class="container2">
                {% for basic in basic %}
            <div class="span_font mypage_font container_x">
                <a style="margin-right: 5px" href="{% url 'main:blog_list' cate=basic %}">{{ basic.category_name }}</a>
            <div class="container_y">
            <a href="{% url 'main:blog_list_crud' cate=basic.category_name %}">
                <img style="height: 17px;" src="{% static 'img/green_plus.png'%}"></a></div>
            </div>
            {% endfor %}
                </div>
        </div>
        </div>
    </div>
</div>
</body>
{% endblock %}
</html>